### PR TITLE
Target data attributes instead of classes

### PR DESCRIPTION
**Pull request by alexcarpenter**
Reference use: http://codepen.io/alexcarpenter/pen/ZQMPrm

### CODE REVIEW

**Comment by bendc** [comment]
What's the rationale for this?

**Comment by alexcarpenter** [comment]
To keep functionality separate from styling.

This way other developers know that it is not for styling purposes.

**Comment by bendc** [comment]
The `class` attribute isn't exclusively made for styling purposes (cfr. HTML5 spec).

**Comment by alexcarpenter** [comment]
👌🏻

**Comment by zslabs** [comment]
While this PR was closed, how do you feel about having a default of that class, but allow users to override with a configuration object that could be passed-in before initialization?

**Pull request closed without merging**
